### ISSUE TITLE
Single Responsibility: Pattern

### ISSUE THREAD

**Issue by icatcher-at** [yfu-is/interactive-world-map#12]
The pattern creation should be extracted to its own method.
Currently there are 2 patterns being created `pattern` and `pattern2`
1. Change naming :stuck_out_tongue_winking_eye:
2. They only differ in the values the use, like color, etc.
3. The creation itself can be a general thing, driven by attributes

**Comment by icatcher-at** [comment]
Additionally it would be great if the options that can be set for the patterns (colors, etc.) could be set by `data` attributes as well.

**Comment by brianstanley** [comment]
Actually the colors can be setted by data :P, data-hover or data-highlight... I take that options from data-\* or for the options hash.
