### ISSUE TITLE
Single Responsibility: Popup

### ISSUE THREAD

**Issue by icatcher-at** [yfu-is/interactive-world-map#13]
The popup should become its own proper class (plugin), with its own settings, etc.
- The interactive-map plugin takes care of interpreting data and rendering the map accordingly. On click it simply displays the popup.
- The popup plugin takes care of rendering the popup with the data that is being feeded.

Future:
Since we will have country information in popups in one map and stories in another it might make sense to have two different popu types that can be used by the same map?

**Comment by brianstanley** [comment]
The popup should become its own plugin but totally independent? I mean there is some stuff that I should use in both plugins beispiel  dataCountries, shoul I send it by parameter to the second plugin or can I extend the plugin for instance?.
So if I extend the popup plugin its not real independent of the map plugin

**Comment by icatcher-at** [comment]
No, it doesn't need to be fully indipendent as a jQuery plugin, since it's using jVectorMap features to display the popup. But it should be capsuled in its own class, with its own interface.
