### ISSUE TITLE
Circle sizes on zoom

### ISSUE THREAD

**Issue by icatcher-at** [yfu-is/interactive-world-map#19]
When trying out the demo, the circles do get resized, but only for the normal pattern. They should also be resized for the hover and highlight pattern.

**Comment by brianstanley** [comment]
ok doing

**Comment by icatcher-at** [comment]
Also... when zooming in, the circles (for me on Firefox) don't look like circles anymore...?

**Comment by brianstanley** [comment]
@icatcher-at  ok I'm checking that , the problem I'm getting it's not completing the whole circle when it's too small

**Comment by icatcher-at** [comment]
@brianstanley Can you try to improve this? Also, the highlight (and hover) patterns don't get resized.
And be prepared to remove that functionality again, once Veronica saw it :wink:

**Comment by brianstanley** [comment]
@icatcher-at  now reduce the size for highlighted and hover,..... but still with the circle issue...
