### ISSUE TITLE
Country flag is not shown in popup

### ISSUE THREAD

**Issue by icatcher-at** [yfu-is/interactive-world-map#26]
When I run the demo, I don't see the country flag in the popup window.

I think it has to do with the fact, that the flag-icons are rendered with an `img` tag. But they should be rendered with a `div`.

**Comment by brianstanley** [comment]
Really? I can see perfectly, also I cloned the actual repo in another folder for try and show good as well. Wierd o.O
![screenshot from 2015-10-27 10 16 40](https://cloud.githubusercontent.com/assets/1711851/10753896/38c79d38-7c94-11e5-8f0f-77be756f3d7e.png)

**Comment by brianstanley** [comment]
Trotzdem in #30 I had to use div instead img
