### ISSUE TITLE
Introduce sensible folder structure

### ISSUE THREAD

**Issue by icatcher-at** [yfu-is/interactive-world-map#3]
I would suggest to have a more understandable folder structure, like so:
- `src` folder holds the `.coffee` and compiled `.js` source files
- `dist` folder holds the compiled and minified `.js` file
- `demo` folder holds all necessary files to run the demo (jVectorMap, *.css, jqery, index.html, etc.)

Take a look at https://github.com/jquery-boilerplate/jquery-boilerplate for a nice example (you can safely ignore all the root files like bower.json, etc.)

**Comment by brianstanley** [comment]
Do I need to create the minified versions as well now?

**Comment by icatcher-at** [comment]
No, that's fine. We'll take care of that later on.
