### ISSUE TITLE
one main links, the other should be regular links

### ISSUE THREAD

**Issue by brianstanley** [yfu-is/interactive-world-map#31]
Asked By Bent.

When we sent the links like 
{ label: 'VISIT COUNTRY WEBSITE', url: 'http://www.yfu.at'}, { label: 'VISIT GOV WEBSITE ', url: 'http://www.yfu.at'} ]}

One should be a button like it's actually but the others should be regular links. So I think one possible solution;
{ label: 'VISIT COUNTRY WEBSITE', url: 'http://www.yfu.at', main: true}, { label: 'VISIT GOV WEBSITE ', url: 'http://www.yfu.at'} ]}

**Comment by icatcher-at** [comment]
Was a mis-interpretation. Ignore for now.
