### ISSUE TITLE
Introduce VERSION file

### ISSUE THREAD

**Issue by icatcher-at** [yfu-is/interactive-world-map#5]
- Introduce a file at the root level, named `VERSION` that holds the current version of the plugin
- Take a look at http://semver.org/ to understand version conventions
- Set the first version to `0.0.1`

**Comment by brianstanley** [comment]
Just a question in semver they say:
How should I deal with revisions in the 0.y.z initial development phase?

The simplest thing to do is start your initial development release at 0.1.0 and then increment the minor version for each subsequent release.

Actually we are just refactoring code without modify the behavior of the program , should we follow that convention like Major.Minor.Patch?
And if we follow we could start 0.1.0 and then 0.1.1 then...

**Comment by icatcher-at** [comment]
Yes, you're absolutely right. Let's go with `0.1.0` :+1:
